
language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules

install:
  - npm install -g dredd
  - npm install

script:
  - export FLOW_BROKER_URL=http://127.0.0.1:3030
  - export DEVICE_MANAGER_URL=http://127.0.0.1:3030
  - bash src/tests/start-test.sh
